### ISSUE TITLE
Infografía: Calidad del software

### ISSUE THREAD

**Issue by Ferch0419** [SistemasTecTlaxiaco/infografia-de-calidad-metztli#1]
[Infografía_Calidad del Software_Fernando Miguel López.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-metztli/files/8795695/Infografia_Calidad.del.Software_Fernando.Miguel.Lopez.pdf)

**Comment by IsraelNicolas61** [comment]
20/20, buen trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
