### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/infografia-de-calidad-metztli#2]
[CALIDAD DE SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-metztli/files/8862939/CALIDAD.DE.SOFTWARE.pdf)

**Comment by IsraelNicolas61** [comment]
20/20, buen trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
