### ISSUE TITLE
Calidad de software Nayeli

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/infografia-de-calidad-metztli#3]
[Calidad de software Nayeli Anai González López.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-metztli/files/8865002/Calidad.de.software.Nayeli.Anai.Gonzalez.Lopez.pdf)

**Comment by IsraelNicolas61** [comment]
20/20, buen trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
