### ISSUE TITLE
INFOGRAFIA -> CALIDAD DE SOFTWARE

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/infografia-de-calidad-metztli#4]
[INFOGRAFIA - CALIDAD DE SOFTWARE -LUIS CARLOS RENDON.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-metztli/files/8884849/INFOGRAFIA.-.CALIDAD.DE.SOFTWARE.-LUIS.CARLOS.RENDON.pdf) 

@josealfredo79

**Comment by IsraelNicolas61** [comment]
20/20, buen trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
